fixed: some deployment environments do return the expected response f…
enketo/enketo-express pull request #270
Opened 2021-06-11 22:48 UTC by MartijnR

…rom process.cwd(),

https://github.com/OpenClinica/enketo-express-oc/issues/485

2021-06-16 21:03 UTC, lognaturel commented
The risk I see with this change is that if just the declaration or the whole `offline-controller` file moves for some reason, offline mode breaks with nothing to catch it. I'd tend to do something more like the `global.X` approach described [here](https://stackoverflow.com/a/18721515/137744) so that only the location of `offline-app-worker-partial.js` needs to be fixed. Would like a more JS-centric perspective from @eyelidlessness.

2021-06-22 19:05 UTC, eyelidlessness requested changes

2021-06-22 19:05 UTC, eyelidlessness commented on app/controllers/offline-controller.js
> +    const partialOfflineAppWorkerScript = fs.readFileSync( path.resolve( __dirname, '../../public/js/src/module/offline-app-worker-partial.js' ), 'utf8' );
I would consider using something like [pkg-dir](https://github.com/sindresorhus/pkg-dir) which is intended for this, and addresses the risk mentioned by @lognaturel.

2021-06-25 21:03 UTC, MartijnR commented on app/models/config-model.js
> +
I figured, it was best to make this centrally accessible in the same way as other such variables (though there is probably scope to rethink that whole model - but beyond the scope of this PR ;)).

2021-06-29 21:46 UTC, merged